// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG2tBXvbFXVmcuYialcwL0IfwxgBg9RbE',
    appId: '1:216860803883:web:5d3bba43c1a112f3027b6e',
    messagingSenderId: '216860803883',
    projectId: 'luxewear-259b1',
    authDomain: 'luxewear-259b1.firebaseapp.com',
    storageBucket: 'luxewear-259b1.firebasestorage.app',
    measurementId: 'G-Q7LB9K9CJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVA35EUGHSpfo_RuwYPyVommN-lcLTA88',
    appId: '1:216860803883:android:cb3affda13e241e4027b6e',
    messagingSenderId: '216860803883',
    projectId: 'luxewear-259b1',
    storageBucket: 'luxewear-259b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXZ6eckZnyH81swZQgmeq7Y_Brm6LS0_Q',
    appId: '1:216860803883:ios:45a2a301cf6958e1027b6e',
    messagingSenderId: '216860803883',
    projectId: 'luxewear-259b1',
    storageBucket: 'luxewear-259b1.firebasestorage.app',
    iosClientId: '216860803883-4e9eplt3ik5498fmq7h61ohs26rcchpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );
}
